# Generated by Django 3.2.9 on 2021-11-26 05:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datetime_begin',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datetime_end',
        ),
        migrations.AddField(
            model_name='task',
            name='date_opening',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
