# Generated by Django 3.2.9 on 2021-11-26 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_date_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_opening',
            field=models.DateField(default=datetime.datetime(2021, 11, 26, 10, 41, 29, 754604, tzinfo=utc)),
        ),
    ]
