# Generated by Django 3.2.9 on 2021-11-26 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_date_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_opening',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
