# Generated by Django 3.2.9 on 2021-12-05 11:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20211205_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time_checked',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 18, 24, 2, 432845)),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
